const db=window.jeiSupabase,$=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const LOCK_KEY='jei_dashboard_unlocked',LOCK_PASSWORD='0514';
const lockScreen=$('#lockScreen'),lockForm=$('#lockForm'),lockPassword=$('#lockPassword'),lockError=$('#lockError');
let user=null,todos=[],discontinued=[],events={},rules=[],noteId=null,selected='',view=new Date();view.setDate(1);
$('#today').textContent=new Intl.DateTimeFormat('ko-KR',{year:'numeric',month:'long',day:'numeric',weekday:'short'}).format(new Date());
function showLogin(){lockScreen.classList.remove('hidden');document.querySelector('.lock-box').innerHTML=`<small>SUPABASE ADMIN</small><h2>한 번만 로그인</h2><p>이 기기에서 처음 한 번만 관리자 계정으로 로그인하면 돼요.</p><form class="lock-form" id="authForm" style="display:grid"><input id="authEmail" type="email" autocomplete="email" placeholder="이메일" required><input id="authPassword" type="password" autocomplete="current-password" placeholder="Supabase 비밀번호" required><button type="submit" style="height:44px">로그인</button></form><p class="lock-error" id="authError"></p>`;$('#authForm').onsubmit=async e=>{e.preventDefault();$('#authError').textContent='로그인 중...';const {error}=await db.auth.signInWithPassword({email:$('#authEmail').value.trim(),password:$('#authPassword').value});if(error){$('#authError').textContent='로그인 실패: '+error.message;return}await startApp()}}
async function gate(){const {data:{session}}=await db.auth.getSession();if(session){user=session.user;lockScreen.classList.add('hidden');await startApp();return}if(localStorage.getItem(LOCK_KEY)==='yes'){showLogin();return}setTimeout(()=>lockPassword.focus(),50);lockForm.addEventListener('submit',e=>{e.preventDefault();if(lockPassword.value===LOCK_PASSWORD){localStorage.setItem(LOCK_KEY,'yes');showLogin()}else{lockError.textContent='비밀번호가 맞지 않아요.';lockPassword.value='';lockPassword.focus()}})}
async function startApp(){const {data:{session}}=await db.auth.getSession();if(!session){showLogin();return}user=session.user;lockScreen.classList.add('hidden');await migrateLocal();await Promise.all([loadTodos(),loadDiscontinued(),loadMemo(),loadRules(),loadEvents()]);drawCalendar()}
async function migrateLocal(){if(localStorage.getItem('jei_supabase_migrated')==='yes')return;
 const {count:tc}=await db.from('todos').select('*',{count:'exact',head:true});if(!tc){const old=JSON.parse(localStorage.getItem('jei_todos')||'[]');if(old.length)await db.from('todos').insert(old.map((x,i)=>({content:x.text,status:x.status==='before'?'시작전':x.status==='doing'?'진행중':'완료',sort_order:i})))}
 const {count:dc}=await db.from('discontinued_items').select('*',{count:'exact',head:true});if(!dc){const old=JSON.parse(localStorage.getItem('jei_discontinued')||'[]');if(old.length)await db.from('discontinued_items').insert(old.map(x=>({product_name:x.product||x.text||'',memo:x.memo||''})))}
 const {count:ec}=await db.from('calendar_events').select('*',{count:'exact',head:true});if(!ec){const old=JSON.parse(localStorage.getItem('jei_events')||'{}');const rows=[];Object.entries(old).forEach(([date,arr])=>arr.forEach(x=>rows.push({event_date:date,title:x.text})));if(rows.length)await db.from('calendar_events').insert(rows)}
 const {count:rc}=await db.from('calendar_keywords').select('*',{count:'exact',head:true});if(!rc){const old=JSON.parse(localStorage.getItem('jei_rules')||'null')||[{keyword:'회의',color:'#e8ddff'},{keyword:'입고',color:'#dff3e8'},{keyword:'마감',color:'#ffe4df'}];if(old.length)await db.from('calendar_keywords').insert(old)}
 const memo=localStorage.getItem('jei_memo');if(memo){const {data}=await db.from('notes').select('id,content').limit(1);if(data?.[0]&&!data[0].content)await db.from('notes').update({content:memo,updated_at:new Date().toISOString()}).eq('id',data[0].id)}
 const {count:gc}=await db.from('board_games').select('*',{count:'exact',head:true});if(!gc){let old=JSON.parse(localStorage.getItem('jei_games')||'null');if(old?.length){const rows=old.map(x=>({title:x.name,genre:x.genre,player_count:x.people||'',play_time:x.time||'',is_expansion:!!x.expansion,image_url:(x.image&&x.image.startsWith('http'))?x.image:''}));await db.from('board_games').insert(rows)}}
 localStorage.setItem('jei_supabase_migrated','yes')}
async function loadTodos(){const {data,error}=await db.from('todos').select('*').order('sort_order').order('created_at',{ascending:false});if(error)return alert(error.message);todos=data||[];drawTodos()}
function stKey(s){return s==='시작전'?'before':s==='진행중'?'doing':'done'}function drawTodos(){['before','doing','done'].forEach(st=>{const arr=todos.filter(x=>stKey(x.status)===st);$('#'+st+'N').textContent=arr.length;$('#'+st+'List').innerHTML=arr.length?arr.map(x=>`<div class="todo-item ${st==='done'?'is-done':''}"><span>${esc(x.content)}</span><div><button onclick="moveTodo('${x.id}')">→</button><button onclick="delTodo('${x.id}')">×</button></div></div>`).join(''):'<p class="empty">비어 있음</p>'});$('#todoCount').textContent=todos.length+'개'}
$('#todoForm').onsubmit=async e=>{e.preventDefault();const v=$('#todoInput').value.trim();if(!v)return;const map={before:'시작전',doing:'진행중',done:'완료'};const {error}=await db.from('todos').insert({content:v,status:map[$('#todoStatus').value]});if(error)return alert(error.message);$('#todoInput').value='';await loadTodos()};window.moveTodo=async id=>{const x=todos.find(t=>t.id===id),next=x.status==='시작전'?'진행중':x.status==='진행중'?'완료':'시작전';await db.from('todos').update({status:next,updated_at:new Date().toISOString()}).eq('id',id);await loadTodos()};window.delTodo=async id=>{await db.from('todos').delete().eq('id',id);await loadTodos()};
async function loadDiscontinued(){const {data}=await db.from('discontinued_items').select('*').order('created_at',{ascending:false});discontinued=data||[];drawDiscontinued()}function drawDiscontinued(){$('#discontinueList').innerHTML=discontinued.length?discontinued.map(x=>`<div class="discontinue-item"><div class="discontinue-copy"><strong>${esc(x.product_name)}</strong>${x.memo?`<span>${esc(x.memo)}</span>`:''}</div><button onclick="doneDiscontinued('${x.id}')">처리완료</button></div>`).join(''):'<p class="empty discontinue-empty">현재 단종 예정 상품이 없어요.</p>'}$('#discontinueOpen').onclick=()=>{$('#discontinueModal').classList.add('show');setTimeout(()=>$('#discontinueProduct').focus(),50)};function closeDiscontinued(){$('#discontinueModal').classList.remove('show')}$('#discontinueClose').onclick=closeDiscontinued;$('#discontinueModal').onclick=e=>{if(e.target===$('#discontinueModal'))closeDiscontinued()};$('#discontinueForm').onsubmit=async e=>{e.preventDefault();const product=$('#discontinueProduct').value.trim(),memo=$('#discontinueMemo').value.trim();if(!product)return;await db.from('discontinued_items').insert({product_name:product,memo});e.target.reset();await loadDiscontinued()};window.doneDiscontinued=async id=>{await db.from('discontinued_items').delete().eq('id',id);await loadDiscontinued()};
async function loadMemo(){let {data}=await db.from('notes').select('*').limit(1);if(!data?.length){const r=await db.from('notes').insert({content:''}).select().single();data=r.data?[r.data]:[]}noteId=data?.[0]?.id||null;$('#memo').value=data?.[0]?.content||''}let memoT;$('#memo').oninput=()=>{clearTimeout(memoT);$('#memoSaved').textContent='저장 중...';memoT=setTimeout(async()=>{if(noteId)await db.from('notes').update({content:$('#memo').value,updated_at:new Date().toISOString()}).eq('id',noteId);$('#memoSaved').textContent='저장됨';setTimeout(()=>$('#memoSaved').textContent='자동 저장',900)},450)};
async function loadEvents(){const {data}=await db.from('calendar_events').select('*');events={};(data||[]).forEach(x=>(events[x.event_date]??=[]).push(x));drawCalendar();drawEventList()}function dateKey(y,m,d){return `${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`}function colorFor(text){const r=rules.find(r=>text.toLowerCase().includes(r.keyword.toLowerCase()));return r?r.color:'#edf0f4'}function drawCalendar(){const y=view.getFullYear(),m=view.getMonth(),first=new Date(y,m,1).getDay(),last=new Date(y,m+1,0).getDate();$('#monthTitle').textContent=`${y}. ${String(m+1).padStart(2,'0')}`;let html='';for(let i=0;i<first;i++)html+='<div class="day blank"></div>';for(let d=1;d<=last;d++){const k=dateKey(y,m,d),es=events[k]||[],today=k===dateKey(new Date().getFullYear(),new Date().getMonth(),new Date().getDate());html+=`<button class="day ${today?'today':''}" onclick="openDay('${k}')"><strong>${d}</strong><div>${es.slice(0,3).map(e=>`<span class="event-chip" style="background:${colorFor(e.title)}">${esc(e.title)}</span>`).join('')}${es.length>3?`<small class="more">+${es.length-3}</small>`:''}</div></button>`}$('#calendar').innerHTML=html}$('#prev').onclick=()=>{view.setMonth(view.getMonth()-1);drawCalendar()};$('#next').onclick=()=>{view.setMonth(view.getMonth()+1);drawCalendar()};window.openDay=k=>{selected=k;const [,m,d]=k.split('-');$('#modalDate').textContent=`${Number(m)}월 ${Number(d)}일`;$('#eventModal').classList.add('show');drawEventList();setTimeout(()=>$('#eventText').focus(),50)};function closeModal(){$('#eventModal').classList.remove('show')}$('#closeModal').onclick=closeModal;$('#eventModal').onclick=e=>{if(e.target===$('#eventModal'))closeModal()};$('#eventForm').onsubmit=async e=>{e.preventDefault();const v=$('#eventText').value.trim();if(!v)return;await db.from('calendar_events').insert({event_date:selected,title:v});$('#eventText').value='';await loadEvents()};function drawEventList(){if(!selected)return;const es=events[selected]||[];$('#eventList').innerHTML=es.length?es.map(e=>`<div class="event-row"><i style="background:${colorFor(e.title)}"></i><span>${esc(e.title)}</span><button onclick="delEvent('${e.id}')">×</button></div>`).join(''):'<p class="empty">등록된 일정이 없어요.</p>'}window.delEvent=async id=>{await db.from('calendar_events').delete().eq('id',id);await loadEvents()};
async function loadRules(){const {data}=await db.from('calendar_keywords').select('*').order('created_at');rules=data||[];drawRules();drawCalendar()}function drawRules(){$('#ruleList').innerHTML=rules.length?rules.map(r=>`<div class="rule"><i style="background:${r.color}"></i><b>${esc(r.keyword)}</b><button onclick="delRule('${r.id}')">×</button></div>`).join(''):'<p class="empty">등록된 키워드가 없어요.</p>'}$('#ruleForm').onsubmit=async e=>{e.preventDefault();const keyword=$('#ruleKeyword').value.trim();if(!keyword)return;const {error}=await db.from('calendar_keywords').insert({keyword,color:$('#ruleColor').value});if(error)return alert(error.message);$('#ruleKeyword').value='';await loadRules()};window.delRule=async id=>{await db.from('calendar_keywords').delete().eq('id',id);await loadRules()};
gate();
